"""initial schema

Revision ID: bc81eb3b5c09
Revises:
Create Date: 2026-09-07 19:31:05.844272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc81eb3b5c09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('entidad', sa.String(length=60), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalle_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_bancario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('concepto_raw', sa.Text(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cuit_detectado', sa.String(length=20), nullable=True),
    sa.Column('nombre_pagador_detectado', sa.String(length=160), nullable=True),
    sa.Column('referencia_detectada', sa.String(length=160), nullable=True),
    sa.Column('subtipo', sa.String(length=10), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=120), nullable=True),
    sa.Column('hash_unico', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'conciliado', 'parcial', 'ignorado_no_alumno', name='estadomovimientoenum'), nullable=False),
    sa.Column('fecha_importacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_unico')
    )
    op.create_table('patron_no_alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patron')
    )
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('tarifa_hora', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sede',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('encargada_nombre', sa.String(length=120), nullable=True),
    sa.Column('encargada_telefono', sa.String(length=30), nullable=True),
    sa.Column('dia_vencimiento_default', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'suspendido', 'baja', name='estadoalumnoenum'), nullable=False),
    sa.Column('fecha_estado', sa.Date(), nullable=True),
    sa.Column('motivo_estado', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sede.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('nivel', sa.String(length=60), nullable=True),
    sa.Column('modalidad', sa.Enum('presencial', 'online', name='modalidadenum'), nullable=False),
    sa.Column('monto_matricula', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_cuota_mensual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cantidad_cuotas', sa.Integer(), nullable=False),
    sa.Column('derecho_examen_monto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sede.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('medio', sa.Enum('transferencia', 'efectivo', name='mediopagoenum'), nullable=False),
    sa.Column('movimiento_bancario_id', sa.Integer(), nullable=True),
    sa.Column('operador_efectivo', sa.String(length=80), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_bancario_id'], ['movimiento_bancario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alias_cobro_alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'alias')
    )
    op.create_table('inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=False),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('descuento_fijo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('anio_reserva', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precio_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('monto_cuota', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_matricula', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referente_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=160), nullable=False),
    sa.Column('cuit_cuil', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('vinculo', sa.Enum('padre', 'madre', 'empresa', 'otro', 'mismo_alumno', name='vinculoenum'), nullable=False),
    sa.Column('es_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_whatsapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('rol', sa.Enum('alumno', 'profesor', 'administrativo', 'owner', name='rolwhatsappenum'), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('cuota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscripcion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('matricula', 'mensual', 'examen', name='tipocuotaenum'), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(length=7), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('monto_original', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_actualizado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'parcial', 'pagada', 'condonada', name='estadocuotaenum'), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imputacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('cuota_id', sa.Integer(), nullable=False),
    sa.Column('monto_imputado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cuota_id'], ['cuota.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imputacion')
    op.drop_table('cuota')
    op.drop_table('usuario_whatsapp')
    op.drop_table('referente_pago')
    op.drop_table('precio_historico')
    op.drop_table('inscripcion')
    op.drop_table('alias_cobro_alumno')
    op.drop_table('pago')
    op.drop_table('curso')
    op.drop_table('alumno')
    op.drop_table('sede')
    op.drop_table('profesor')
    op.drop_table('patron_no_alumno')
    op.drop_table('movimiento_bancario')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
